# Generated by Django 3.0.6 on 2020-05-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Class', models.TextField()),
                ('DueDate', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
